# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56197d552ea0b415dc5e405bfa60c4ba28274fa78a0fc51c7248c0271abe4e371a7f6ee419aff4b909219847f6701f8de356a84c8c31153d315132082a79cf5e

test:
  secret_key_base: 3457c92bfb374ef6cb453ac99a16f3293a9c6b0820d9b7b3e98f71c17b2d22c0b30087689bdd8a99cace16dce2940a4751adc54d95fc2ce79d2806ab8605e540

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
